destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /:year/:month/:title
exclude: [config, CNAME, Rakefile, Capfile, _site.tar.gz, tomafro.net]
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex