--- 
permalink: /:year/:month/:title
maruku: 
  png_dir: images/latex
  png_url: /images/latex
  use_tex: false
  use_divs: false
lsi: false
minutes: "     747.1"
destination: ./_site
days: "       0.5"
markdown: maruku
exclude: 
- config
- CNAME
- Rakefile
- Capfile
- _site.tar.gz
- tomafro.net
pygments: true
auto: true
server_port: 4000
