--- 
permalink: /:year/:month/:title
maruku: 
  png_dir: images/latex
  png_url: /images/latex
  use_divs: false
  use_tex: false
minutes: "    5865.9"
lsi: false
days: "       4.1"
destination: ./_site
exclude: 
- config
- CNAME
- Rakefile
- Capfile
- _site.tar.gz
- tomafro.net
markdown: maruku
pygments: true
auto: true
pretty_style: html_extension
server_port: 4000
